### ISSUE TITLE
What is the `Testing` deployment environment for?

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope#143]
I notice that when I push to a PR branch, it triggers some kind of build of this `Testing` "Deployment"...
![Screenshot 2024-05-06 at 1 03 17 PM](https://github.com/wildlife-dynamics/ecoscope/assets/62192187/1b136675-b630-4f66-bdab-8a1d7a1e7408)
![Screenshot 2024-05-06 at 1 02 46 PM](https://github.com/wildlife-dynamics/ecoscope/assets/62192187/4b38e316-9fa7-4b34-8428-8f120982746f)

what is this and why do we need it? 😃

**Comment by atmorling** [comment]
It's set [here](https://github.com/wildlife-dynamics/ecoscope/blob/b3b9d1543eee5357ef9b2df8a4135d47d40f39d4/.github/workflows/main.yml#L5) and refers to the environment in the repos [settings](https://github.com/wildlife-dynamics/ecoscope/settings/environments) where the ER/EE keys used for testing are configured
