### ISSUE TITLE
Resample issues

### ISSUE THREAD

**Issue by Ankabedettidk** [wildlife-dynamics/ecoscope#15]
The resample section isn't working in Relocations and Trajectories Notebook:

new_relocs=traj.to_relocations() 
AttributeError: 'Trajectory' object has no attribute 'to_relocations'

I then used a pip install from a previous version - but that just duplicates points instead of projecting them on the trajectory.
Example of 4hourly data upsampled to hourly: 

2019-06-05 01:00:32+00:00 | POINT (32.1653 -23.802133333333302)
2019-06-05 02:00:32+00:00 | POINT (32.1653 -23.802133333333302)
2019-06-05 03:00:32+00:00 | POINT (32.1653 -23.802133333333302)
2019-06-05 04:00:32+00:00 | POINT (32.1830833333333 -23.766116666666708)
2019-06-05 05:00:32+00:00 | POINT (32.1830833333333 -23.766116666666708)
2019-06-05 06:00:32+00:00 | POINT (32.1830833333333 -23.766116666666708)
2019-06-05 07:00:32+00:00 | POINT (32.1830833333333 -23.766116666666708)
2019-06-05 08:00:32+00:00 | POINT (32.1874166666667 -23.76808333333329)
2019-06-05 09:00:32+00:00 | POINT (32.1874166666667 -23.76808333333329)
2019-06-05 10:00:32+00:00 | POINT (32.1874166666667 -23.76808333333329)
2019-06-05 11:00:32+00:00 | POINT (32.1874166666667 -23.76808333333329)

**Comment by zakhusayn** [comment]
@Ankabedettidk The current version of ecoscope `1.0.1` in PyPI repository does not have all the methods and features that has been recently been added in ecoscope and the notebooks tutorials in [ecoscope.io ](ecoscope.io)is ahead of its time. It is showing all the new updates that have made on the notebooks and merged to master branch.

if you would like to try out the new updates made on ecoscope before the new release, try installing it directly from github.
```sh
!pip install -e "git+https://github.com/wildlife-dynamics/ecoscope.git#egg=ecoscope"
```

**Comment by cath34** [comment]
Hi Anka, sorry for taking some time to answer, I didn't saw your issue. It's now fixed and merged to master. If you encounter any problems, please let us know!

**Comment by Ankabedettidk** [comment]
Thank you so much for fixing this ! It is such a valuable tool to have access to :)

**Comment by Ankabedettidk** [comment]
I just tried it and it is now giving me this issue again.. I used a new colab notebook on ecoscope.io

Convert a Trajectory object to a Relocation object
new_relocs = traj.to_relocations()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-22-e58ef17e586c>](https://localhost:8080/#) in <module>
----> 1 new_relocs = traj.to_relocations()

[/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in __getattr__(self, name)
   5485         ):
   5486             return self[name]
-> 5487         return object.__getattribute__(self, name)
   5488 
   5489     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Trajectory' object has no attribute 'to_relocations'

**Comment by cath34** [comment]
Can you try to use `!pip install git+https://github.com/wildlife-dynamics/ecoscope` at the beginning of your Notebook? If it doesn't work, please send me your notebook by e-mail (catherinevilleneuve6@gmail.com) in order for me to understand better what is happening.

**Comment by Ankabedettidk** [comment]
Hi Cath34, it worked with the suggested pip install. Thank you so so much for this !
