### ISSUE TITLE
install dependency issue with astropy

### ISSUE THREAD

**Issue by chrisgnicholas** [wildlife-dynamics/ecoscope#176]
hi - I'm do a fresh install on a new MAC; I made a new virtual environment with Python 3.12.3, and while doing: 

python setup.py install

I'm encountering:

...
Reading https://pypi.org/simple/astropy/
Downloading https://files.pythonhosted.org/packages/03/1e/b597f9e854c09b1a1f558cf17a671ad886d9ee02df760027d4b4a788653a/astropy-6.1.0-cp312-cp312-macosx_11_0_arm64.whl#sha256=f6bf9990282c5732c8fca053c5c54116cbf79b6a7a50549f0f1f8e156d614496
Best match: astropy 6.1.0
Processing astropy-6.1.0-cp312-cp312-macosx_11_0_arm64.whl
Installing astropy-6.1.0-cp312-cp312-macosx_11_0_arm64.whl to /Users/cnicholas/src/ecoscope/.venv/lib/python3.12/site-packages
Adding astropy 6.1.0 to easy-install.pth file
detected new path './six-1.16.0-py3.12.egg'
Installing fits2bitmap script to /Users/cnicholas/src/ecoscope/.venv/bin
Installing fitscheck script to /Users/cnicholas/src/ecoscope/.venv/bin
Installing fitsdiff script to /Users/cnicholas/src/ecoscope/.venv/bin
Installing fitsheader script to /Users/cnicholas/src/ecoscope/.venv/bin
Installing fitsinfo script to /Users/cnicholas/src/ecoscope/.venv/bin
Installing samp_hub script to /Users/cnicholas/src/ecoscope/.venv/bin
Installing showtable script to /Users/cnicholas/src/ecoscope/.venv/bin
Installing volint script to /Users/cnicholas/src/ecoscope/.venv/bin
Installing wcslint script to /Users/cnicholas/src/ecoscope/.venv/bin

Installed /Users/cnicholas/src/ecoscope/.venv/lib/python3.12/site-packages/astropy-6.1.0-py3.12-macosx-14.0-arm64.egg
error: numpy 2.0.0rc2 is installed but numpy<2 is required by {'astroplan'}

(.venv)

**Comment by atmorling** [comment]
I'm able to replicate this in a fresh environment using `python setup.py install`, however in a fresh environment running `pip install .`, the `numpy` dependency is resolved to the correct `<2` version.

Can you try running `pip install .` rather than invoking `setup.py` directly?

**Comment by atmorling** [comment]
Closed with #191 - the `setup.py` route has been removed
