### ISSUE TITLE
Research: patrol observations download optimization

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#182]
Review the process for polling patrol observations from ER using the ecoscope ER_IO client which in turn uses the er_client library. Is this process optimized and how can we make it faster? We currently use the get_objects_multithreaded() function in er_client but there is another async method used by Gundi which we should explore.

**Comment by Yun-Wu** [comment]
Performance benchmark:
- get_patrols: 14 days: 8.3s, 1 month: 5.89s, 8 months: 37.3s
- get_patrol_observations: 14 days: 2min 6s, 1month: 3min54s, 8 months: 23min44s

**Comment by Yun-Wu** [comment]
Reduce the number of http calls: [Remove repeated get_patrol_types call #185](https://github.com/wildlife-dynamics/ecoscope/pull/185)

**Comment by Yun-Wu** [comment]
Synced with @walljcg offline with the following action items:
1. Sync with Joshua to support more efficient endpoints on the server side for patrol observations
2. Sync with Chris Doering to check if they are using the ER async client and its performance
3. Sync with Chris Jones on the progress of ER data warehouse.

**Comment by cisaacstern** [comment]
This is so incredibly valuable, TYSM! 🙏
