### ISSUE TITLE
Generate value -> display remap dictionary from event_type schema

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#190]
We want to be able to create a dictionary for mapping values to display values by reading the json schema of an ER event type. Will require querying the Json Schema for a particular EventType through the ER API. This functionality should extend the ecoscope ER_IO client.

**Comment by atmorling** [comment]
Turns out we get display names from `activity/events/eventtypes` (which we already wrap as `get_event_types()`) without having to query specifically for the schema of each EventType

**Comment by atmorling** [comment]
@walljcg is the main story behind this task to provide the display names to the configuration dialog within `ecoscope-web`?

**Comment by atmorling** [comment]
This has been done in the async client #198
