### ISSUE TITLE
Remove empty assertion from er_io get_sources() and get_subjects()

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#239]
I think we should remove the 'assert not df.empty' lines from both the get_sources() and get_subjects() functions in ER_IO. It should be up to the user to handle what to do when a dataframe comes back empty and not error out in the function.

**Comment by atmorling** [comment]
I'll update these to be `if not df.empty` as we're doing some processing after the assertion that assumes the presence of data
