### ISSUE TITLE
SPKIE: Ephem Library for astronomical calculations

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#284]
See whether the ephem library makes more sense for diurnal calculations. And can we calculate moonlight (i.e., moon disc fraction?) 

https://pypi.org/project/ephem/

**Comment by Yun-Wu** [comment]
This ([notebook](https://colab.research.google.com/drive/1IqEd4ctNO_6zyEDTnvooUgdmM2wfnu1F#scrollTo=_UMGKvZhwaHv)) compares astropy with ephem. Ephem is much faster than astropy. With Mali’s data, astropy takes 1min 20s and ephem uses less than 10s. However, there is 8% difference between the two results (Astropy: 1.52 vs Ephem: 1.41) I did some quick check (the last section of the notebook) and the sunrise time has 1m32s difference for the same day and location. Astropy should have a more accurate and up-to-date algorithm. But based on Jake's early patrol in Kilifi, there's a bigger deviation with Astropy
```
Comparing sunrise times for 2024-10-09 at lat=3.62396, lon=39.87446
ephem:   2024-10-10 03:08:07.211622+00:00
astropy: 2024-10-09 03:09:22.057744
```

**Comment by walljcg** [comment]
Yep, sunrise that day from Kilifi was between 6:02 - 06:04 EAT.
