### ISSUE TITLE
Dataframes of len 1 passed to _create_multitraj do not always have column "extra__subject_id", raising KeyError

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope#328]
As observed in debugging https://github.com/wildlife-dynamics/ecoscope-platform-workflow-issues/issues/9, dataframes landing on this line

https://github.com/wildlife-dynamics/ecoscope/blob/9041cea812d13d766f673e0d357bd0c9891de38a/ecoscope/base/base.py#L384

do not always have the `"extra__subject_id"` column, raising a KeyError on what is intended to be a warning, if so.

In the linked (private) workflow debugging issue, this error was avoided by monkey-patching `"groupby_col"` instead, at @atmorling's suggestion, but I am not sure if this is the preferred fix or not.

**Comment by atmorling** [comment]
I think using `groupby_col` makes sense since `extra__*` (currently) has the implication that it might be dropped at any time
