### ISSUE TITLE
Relocations junk_status col can be `object` (when it should be `bool`), causing error on `Relocations.remove_filtered`

### ISSUE THREAD

**Issue by cisaacstern** [wildlife-dynamics/ecoscope#329]
As observed in course of debugging https://github.com/wildlife-dynamics/ecoscope-platform-workflow-issues/issues/9.

The following [invocation of `Relocations.remove_filtered` in workflows](https://github.com/wildlife-dynamics/ecoscope-workflows/blob/7ae1dce6a347e2e1186e1bf5c2b515a7be26c703/src/ecoscope-workflows-ext-ecoscope/ecoscope_workflows_ext_ecoscope/tasks/preprocessing/_preprocessing.py#L39-L45)

calls into

https://github.com/wildlife-dynamics/ecoscope/blob/9041cea812d13d766f673e0d357bd0c9891de38a/ecoscope/base/base.py#L101-L110

In this block, if the `junk_status` column was observed to be sometimes (at least in one case, for the linked workflow failure) of type `object`. In this situation, the `.remove_filtered` call fails with a KeyError.

**Comment by cisaacstern** [comment]
I am trying to rerun the above failed workflow with this diff monkey-patched into ecoscope:

```diff
    def remove_filtered(self, inplace=False):
        if inplace:
            frame = self
        else:
            frame = self.copy()

+       if not frame["junk_status"].dtype == bool:
+           warnings.warn(
+               f"junk_status column is of type {frame['junk_status'].dtype}, expected `bool`. "
+               "Attempting to automatically convert."
+           )
+           frame["junk_status"] = frame["junk_status"].astype(bool)

        frame.query("~junk_status", inplace=True)

        if not inplace:
            return frame
```

**Comment by atmorling** [comment]
I'm going to add this coercion as an extra safeguard but the issue actually stems from my earlier bug fix to handle single reloc subjects
