### ISSUE TITLE
Overhaul ecoscope.io.utils.download_file()

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#78]
The download_file() function needs to be expanded to support Dropbox urls, and GDrive urls. Let's look at using fsspec:. For example: 

with fsspec.open(url, mode='rt',) as file:
  config = json.loads(file.read())
config

**Comment by atmorling** [comment]
Seems like the fsspec gdrive implementation [isn't released yet](https://github.com/fsspec/gdrivefs/issues/21) and so can't be pip installed.

Are we only concerned with supporting Dropbox and Gdrive?

**Comment by atmorling** [comment]
Closing this as it's a duplicate of https://github.com/wildlife-dynamics/ecoscope/issues/96
