### ISSUE TITLE
SPIKE: use Kaleido for image exports

### ISSUE THREAD

**Issue by atmorling** [wildlife-dynamics/ecoscope#86]

**Comment by doug-nimblegravity** [comment]
Probably not as simple as we think. We may need to write our own plugin to support folium or leaflet.

**Comment by atmorling** [comment]
I think we can close this - to me the cons outweigh the pros

#### Pros
- Removes selenium dependency and would help clean up `ecoscope.init()`
- Silver bullet for PNG and PDF exports
#### Cons
- Effort in creating a plugin to support Folium 
- Would have to be re-implemented (and more likely discarded as there's better options) in a deck.gl based EcoMap
- The project seems to get [little/no support](https://github.com/plotly/Kaleido/issues/150) for open issues
