### ISSUE TITLE
Method to download files

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#96]
Our current implementation is here: https://github.com/wildlife-dynamics/ecoscope/blob/d0650725ed91d2cb1d6b3decc24be3486302dd00/ecoscope/io/utils.py#L28

Need to make this more generalized to support download of files: 

- [ ] Dropbox
- [ ] Google Drive
- [ ] Zipped files (and unzip them)

- explore using fsspec as used by GeoPandas?

**Comment by Yun-Wu** [comment]
Done
